// New mobile summaries and controls. Approved long-form copy lives separately.
export const mobileCopy = {
  service: ['Osobní trénink a pohybová praxe · Praha', 'Personal training and movement practice · Prague'],
  book: ['Domluvit lekci', 'Book a session'],
  clients: ['Vstup pro klienty', 'Client login'],
  menu: ['Otevřít menu', 'Open menu'],
  close: ['Zavřít menu', 'Close menu'],
  intro: ['O mém přístupu', 'About my approach'],
  homeLead: ['Síla. Jistota v pohybu. Vlastní praxe.', 'Strength. Confidence in movement. Your own practice.'],
  audienceOne: ['Trénink, ke kterému se rád vracíš.', 'Training you enjoy returning to.'],
  audienceTwo: ['Směr místo nahodilých lekcí.', 'Direction for every session.'],
  clearPriorities: ['Jasné hodnoty', 'Clear values'],
  collabLead: ['Osobně v Praze. Nebo odkudkoli.', 'In person in Prague. Or wherever you are.'],
  formatDetail: ['Jak může spolupráce vypadat', 'What working together can look like'],
  aboutDetail: ['Zkušenosti a vzdělání', 'Experience and education'],
  practiceDetail: ['Jaký je v tom rozdíl', 'What is the difference'],
  anchorsDetail: ['Jak kotvy drží pohromadě', 'How the anchors work together'],
  reflectionDetail: ['Co všechno do praxe vstupuje', 'What shapes your practice'],
  nameDetail: ['Odkud pochází tanmay', 'Where tanmay comes from'],
  aboutLead: ['Síla, kalistenika a vlastní cesta.', 'Strength, calisthenics and a path of my own.'],
  storyDetail: ['Jak začínal návrat', 'Where the return began'],
  qualifications: ['Podrobně o vzdělání', 'Education in detail'],
  collaborationIntro: ['Jak zvolíme formu spolupráce', 'How we choose a way to work'],
  needsDetail: ['Když zatím nevíš, kde začít', 'If you are unsure where to begin'],
  betweenDetail: ['Tvoje praxe mezi setkáními', 'Your practice between sessions'],
  betweenParagraph: ['Při delší spolupráci máš v klientské aplikaci svůj plán, termíny, záznamy a zpětnou vazbu na jednom místě.', 'In longer-term work, your plan, sessions, records and feedback live together in the client app.'],
  browse: ['Posuň a prohlédni další', 'Swipe to explore'],
  previous: ['Předchozí možnost', 'Previous option'],
  next: ['Další možnost', 'Next option'],
  home: ['Domů', 'Home'],
  collaboration: ['Spolupráce', 'Work with me'],
  practice: ['Praxe', 'Practice'],
  about: ['O mně', 'About me'],
  privacy: ['Soukromí', 'Privacy'],
  skip: ['Přejít na obsah', 'Skip to content'],
  email: ['Napsat e-mail', 'Send an email'],
  wa: ['Napsat na WhatsApp', 'Message on WhatsApp'],
  prices: ['Ceník', 'Prices'],
  explore: ['Prohlédnout nabídku', 'Explore the options'],
  continue: ['Pokračovat', 'Continue'],
  prague: ['Praha · online', 'Prague · online'],
  rootsDetail: ['Z čeho moje práce vychází', 'Where my work comes from'],
  forestAlt: ['Pohled zdola mezi korunami borovic, s postavou v teplém večerním světle.', 'An upward view through pine canopies, with a figure in warm evening light.'],
  handstandAlt: ['Stoj na rukou, černobílá fotografie celé postavy.', 'A handstand, black-and-white photograph of the whole figure.'],
  saltoAlt: ['Kryštof v saltu, černobílá fotografie pohybu.', 'Kryštof mid-salto, a black-and-white movement photograph.'],
} as const;
export type MobileLanguage = 'cs' | 'en';
export const mobileFormatSummaries = [
  ['Jedno setkání nebo delší vedení.', 'One session or longer-term guidance.'],
  ['Vlastní úroveň. Společný rytmus.', 'Your own level. A shared rhythm.'],
  ['Plán, zpětná vazba a průběžné úpravy.', 'A plan, feedback and ongoing adjustments.'],
] as const;
export const mobileText = (key: keyof typeof mobileCopy, lang: string) => mobileCopy[key][lang === 'en' ? 1 : 0];
