#!/usr/bin/env python3
"""
build-fonts.py · authoring tool, never part of `npm run build`
----------------------------------------------------------------------
Puts the four Brand V2 typefaces into `public/fonts/` as first party
woff2 files, subset to the alphabet this site can actually set, and
writes `public/fonts/tanmay-fonts.css`.

    pip install fonttools brotli
    python3 scripts/build-fonts.py

Why the site does not link Google Fonts any more:
  1. The footer says there are no cookies, no analytics and no third
     parties. A font request to another company's server would make the
     last of those false, because the visitor's IP address reaches it.
  2. A cross origin stylesheet is a render blocking round trip before
     the first font byte is even requested.
  3. All four families are SIL Open Font License 1.1, which permits
     hosting and subsetting. `public/fonts/OFL.txt` carries the licence.

Why subset:
  Google's own `latin-ext` slice carries the whole of Latin Extended
  plus IPA and phonetic ranges. Czech needs about thirty of those
  glyphs. Subsetting to Latin-1 plus Latin Extended-A plus the
  punctuation the brand uses takes the four faces from roughly 260 kB to
  well under half of that, with no visible difference. Anything outside
  the set falls back to Georgia or the system sans, which is a visible
  but harmless degradation, never a missing glyph box.

The full source faces are fetched with npm --no-save. They never enter
package.json, so the Cloudflare build never installs them.
"""
import shutil
import subprocess
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "fonts"
CACHE = ROOT / ".fonts-tmp"

# family, npm package, weight folder, ttf name, css family, weight, style
FACES = [
    ("cormorant-garamond", "300Light", "CormorantGaramond_300Light.ttf", "Cormorant Garamond", 300, "normal"),
    ("cormorant-garamond", "400Regular", "CormorantGaramond_400Regular.ttf", "Cormorant Garamond", 400, "normal"),
    ("cormorant-garamond", "400Regular_Italic", "CormorantGaramond_400Regular_Italic.ttf", "Cormorant Garamond", 400, "italic"),
    ("eb-garamond", "400Regular", "EBGaramond_400Regular.ttf", "EB Garamond", 400, "normal"),
    ("eb-garamond", "400Regular_Italic", "EBGaramond_400Regular_Italic.ttf", "EB Garamond", 400, "italic"),
    ("dm-sans", "400Regular", "DMSans_400Regular.ttf", "DM Sans", 400, "normal"),
    ("dm-sans", "500Medium", "DMSans_500Medium.ttf", "DM Sans", 500, "normal"),
    ("barlow-condensed", "400Regular", "BarlowCondensed_400Regular.ttf", "Barlow Condensed", 400, "normal"),
    ("barlow-condensed", "500Medium", "BarlowCondensed_500Medium.ttf", "Barlow Condensed", 500, "normal"),
]

# Latin-1, Latin Extended-A, and the punctuation the brand actually sets.
UNICODES = [
    "U+0000-00FF",   # ASCII and Latin-1, covers á é í ó ú ý and friends
    "U+0100-017F",   # Latin Extended-A, covers č ď ě ň ř š ť ů ž
    "U+0192", "U+02C6", "U+02DA", "U+02DC",
    "U+2010-2015",   # hyphens and dashes
    "U+2018-201E",   # quotes, including the Czech „ "
    "U+2020-2022",   # dagger, bullet
    "U+2026",        # ellipsis
    "U+2030", "U+2039-203A", "U+2044",
    "U+20AC",        # euro
    "U+2122",        # trade mark
    "U+2190-2193",   # arrows, the site uses →
    "U+2212", "U+2215",
    "U+00A0",        # the non breaking space Czech typesetting inserts
    "U+00B7",        # the middle dot the brand separates words with
    "U+FEFF", "U+FFFD",
]
CSS_RANGE = ",".join(UNICODES)


def ensure_sources():
    CACHE.mkdir(exist_ok=True)
    if (CACHE / "node_modules").exists():
        return
    (CACHE / "package.json").write_text('{"name":"fonts-tmp","private":true}')
    pkgs = sorted({"@expo-google-fonts/" + f[0] for f in FACES})
    print("fetching", " ".join(pkgs))
    subprocess.run(
        ["npm", "install", "--no-save", "--no-audit", "--no-fund", *pkgs],
        cwd=CACHE, check=True, stdout=subprocess.DEVNULL,
    )


def main():
    ensure_sources()
    OUT.mkdir(parents=True, exist_ok=True)
    for f in OUT.glob("*.woff2"):
        f.unlink()

    css = [
        "/* Generated by scripts/build-fonts.py. Do not edit by hand.",
        "   Brand V2 typefaces, served first party, subset to Latin-1 plus",
        "   Latin Extended-A. SIL OFL 1.1, see OFL.txt. */",
    ]
    total = 0
    for pkg, folder, ttf, family, weight, style in FACES:
        src = CACHE / "node_modules" / "@expo-google-fonts" / pkg / folder / ttf
        if not src.exists():
            raise SystemExit(f"missing source face: {src}")
        name = f"{pkg}-{weight}-{style}.woff2"
        dst = OUT / name

        options = subset.Options()
        options.flavor = "woff2"
        options.with_zopfli = True
        options.desubroutinize = False
        options.layout_features = ["kern", "liga", "clig", "calt", "ccmp", "locl", "mark", "mkmk"]
        options.name_IDs = ["*"]
        options.name_legacy = False
        options.notdef_outline = False
        options.recalc_bounds = True
        options.drop_tables += ["DSIG"]

        font = subset.load_font(str(src), options)
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=subset.parse_unicodes(CSS_RANGE))
        subsetter.subset(font)
        subset.save_font(font, str(dst), options)
        font.close()

        size = dst.stat().st_size
        total += size
        print(f"  {name:<44}{size / 1024:>7.1f} kB")
        css.append(
            f"@font-face{{font-family:'{family}';font-style:{style};font-weight:{weight};"
            f"font-display:swap;src:url(/fonts/{name}) format('woff2');unicode-range:{CSS_RANGE}}}"
        )

    (OUT / "tanmay-fonts.css").write_text("\n".join(css) + "\n", encoding="utf8")

    licence = []
    for pkg in sorted({f[0] for f in FACES}):
        d = CACHE / "node_modules" / "@expo-google-fonts" / pkg
        text = None
        for n in ("LICENSE", "LICENSE.md", "LICENSE.txt", "OFL.txt"):
            if (d / n).exists():
                text = (d / n).read_text(encoding="utf8", errors="replace")
                break
        licence.append(f"===== {pkg} =====\n\n" + (text or "SIL Open Font License 1.1\n"))
    (OUT / "OFL.txt").write_text("\n\n".join(licence), encoding="utf8")

    print(f"{len(FACES)} faces, {total / 1024:.0f} kB total in public/fonts/")


if __name__ == "__main__":
    main()
